apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bastion
spec:
  serviceName: 'bastion-service'
  selector:
    matchLabels:
      app: bastion
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bastion
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: bastion
        image: ubuntu:20.04
        volumeMounts:
          - name: pvc1
            mountPath: /data
        command: ["tail", "-f", "/dev/null"]
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: pvc1
      annotations:
        volume.beta.kubernetes.io/storage-class: "gp2"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
