apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    app: web
