apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-northeast-2:644421735833:certificate/cbfed9f8-42f5-4eae-aa28-8a3fca1d0632
    external-dns.alpha.kubernetes.io/hostname: cat.bitvleotest.com
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
spec:
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: https
    port: 443
    targetPort: 8000
  selector:
    app: web